### ISSUE TITLE
Repository license

### ISSUE THREAD

**Issue by ThomasKierski** [pieper/SlicerParallelProcessing#14]
Hi @pieper, would you be open to adding a license to this repository? I would like to use some of this code in my own work. For our application, we have extended the `Process` class in this repo to break out some `MONAILabel` functionality into a separate process which has improved performance quite a bit.

**Comment by pieper** [comment]
Good point:  Closed with #ddf5337

@ThomasKierski if you can share your example a link from here would be nice.  Even better if you can contribute back to the upstream MONAI Label @ diazandr3s
