### ISSUE TITLE
When run it with Slicer version 4.11.20210226 got error message

### ISSUE THREAD

**Issue by 1939938853** [pieper/SlicerParallelProcessing#9]
Hello,

When I ran SlicerParallelProcessing as told here for the latest stable version of  Slicer version 4.11.20210226, I got an error message said  Slicer version 4.23 needed. What should I do? 

Slicer version 4.23  not work for SlicerIGSIO.

./path/to/Slicer --additional-module-paths path/to/SlicerProcesses/Processes

**Comment by pieper** [comment]
Maybe you are following a tutorial by @ungi ?  Maybe you also mean 4.13.x (a recent Preview build)? (There is no 4.23).  As far as I can tell IGSIO and the ParallelProcessing extension are available in the current preview build.

If you are still having issues, provide a more specific report with some more details and context.
